### ISSUE TITLE
Crash app tablet

### ISSUE THREAD

**Issue by Angelk90** [theScrabi/NewPlayer#6] opened 2024-10-30 19:57 UTC
Hi @theScrabi ,  I installed apk from the following [link](https://github.com/TeamNewPipe/NewPlayer/releases/download/v0.0.2-alpha/NewPlayer-testapp-v0.0.2-alpha_debug.apk) on a tablet but when I start the app it always crashes.

Info tablet: Samsung T585 Galaxy Tab A 10.1" 2016 LTE Android 8.1.0

**Comment by theScrabi** [comment] 2024-10-31 14:44
You're issue might be a duplicate of this one: https://github.com/TeamNewPipe/NewPlayer/issues/4

Try this build:
https://github.com/user-attachments/files/17561790/NewPlayer-testapp-0.0.2-alpha_fixedcarash_debug.zip

**Comment by Angelk90** [comment] 2024-10-31 15:11
@theScrabi : This version is started.
Some things I noticed:

1) As soon as I start the app, I don't press anything, the player tries to load something is this normal?
2) I turned off the internet, as soon as I start the app, I don't press anything, the player tries to load, it shouldn't give me any errors.
3) No internet, I click on `Start 6502 Stream`, app crash, I think it needs some checks to see if there is internet.
4) Same problem as 3) if I click on `Start IMU Stream`, `Append 6502 Stream` and `Append IMU Stream`, on all the other buttons when I press nothing happens.
5) Can I ask you does it work correctly with live videos?
Example: https://www.youtube.com/watch?v=lDcWeklf6DI
6) Can I ask you if you can implement in the future features like, wifi transmission on devices, video loop and displaying live chat messages when enabled.

**Closed as completed** 2024-11-10 19:48 UTC
Labels: duplicate

**Comment by theScrabi** [comment] 2024-11-10 19:51
These are multiple non-related issues you are writing now. These are not related to the original issue, so I'm closing this.
Please also be aware that NewPlayer is currently in Alpha state so it's not yet expected that everything works smoothly.
